application: lp-podcast
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: src/static/favicon.ico
  upload: src/static/favicon\.ico

- url: /static
  static_dir: src/static
  secure: always

- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin
  secure: always

- url: .*
  script: main.app

- url: /api/.*
  script: main.app
  secure: always

- url: /.*
  script: main.app
  login: required
  auth_fail_action: redirect
  secure: always

libraries:
  - name: ssl
    version: latest

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - (.*/test/.*)
  - (.*/test/.*)
  - (venv/.*)
