runtime: python39

instance_class: F1

entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 1 --threads 2

handlers:
- url: /favicon\.ico
  static_files: src/static/favicon.ico
  upload: src/static/favicon\.ico

- url: /static
  static_dir: src/static
  secure: always

- url: /admin/.*
  script: auto
  login: admin
  secure: always

- url: .*
  script: auto

- url: /api/.*
  script: auto
  secure: always

- url: /.*
  script: auto
  login: required
  auth_fail_action: redirect
  secure: always

